#!/bin/bash

forceful_kill() {
    pkill -9 wlsunset
    sleep 0.2
}

if pgrep -x "wlsunset" > /dev/null; then
    killall wlsunset 2>/dev/null
    
    if pgrep -x "wlsunset" > /dev/null; then
        forceful_kill
    fi
    dunstify "WLSunset disabled"
else
    wlsunset -t 1500 &
    dunstify "WLSunset enabled with temp 1500K"
fi
