inherits = "catppuccin_mocha"
"ui.background" = { bg = "" }
"ui.text" = { bg = "" }
"ui.gutter" = { bg = "#181825" }
"ui.gutter.selected" = { bg = "#000000" }
"ui.linenr.selected" = { fg = "#45475a" }
