workspace = 1, layout:scrolling, gapsin:5
# workspace = 1, layout:monocle

windowrule {
  name = windowrule-1
  workspace = 1
  match:title = ^(.*Mozilla Firefox)$
}

windowrule {
  name = windowrule-2
  workspace = 1
  match:class = ^(zen)$
}

windowrule {
  name = windowrule-3
  workspace = 2
  match:title = ^(kitty)$
}

windowrule {
  name = windowrule-4
  workspace = 3
  match:class = ^(obsidian)$
}

windowrule {
  name = windowrule-5
  workspace = 3
  match:title = ^(osu\!)$
}

windowrule {
  name = windowrule-6
  workspace = 4
  match:title = ^(discord)$
}

windowrule {
  name = windowrule-7
  workspace = 4
  match:title = ^(vesktop)$
}


# windowrule {
#   name = windowrule-8
#   opacity = 0.91 override 1.0 override
#   match:class = ^(kitty)$
# }
