theme = "snazzy_t"
# theme = "catppuccin_mochaBG"
# theme = "ao"

[editor]
line-number = "relative"
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
Z = {Q = ":quit!", Z = ":write-quit!"}
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.select]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
Z = {Q = ":quit!", Z = ":write-quit!"}
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
X = "extend_line_above"
